import type { ColorPalette } from "../types/color.types";

export const colorPalettes: ColorPalette[] = [
  {
    id: "warm",
    label: "Colores Cálidos",
    colors: [
      { name: "Amarillo", hex: "#facc15" },
      { name: "Naranja", hex: "#f97316" },
      { name: "Rojo", hex: "#ef4444" },
      { name: "Coral", hex: "#fb7185" },
      { name: "Melocotón", hex: "#fda4af" },
      { name: "Caramelo", hex: "#eab308" },
      { name: "Terracota", hex: "#d97706" },
      { name: "Rosa Intenso", hex: "#f43f5e" },
    ],
  },
  {
    id: "cool",
    label: "Colores Fríos",
    colors: [
      { name: "Azul", hex: "#3b82f6" },
      { name: "Cian", hex: "#06b6d4" },
      { name: "Verde", hex: "#10b981" },
      { name: "Turquesa", hex: "#2dd4bf" },
      { name: "Verde Menta", hex: "#5eead4" },
      { name: "Lavanda", hex: "#818cf8" },
      { name: "Azul Noche", hex: "#1e3a8a" },
      { name: "Verde Bosque", hex: "#065f46" },
    ],
  },
  {
    id: "rainbow",
    label: "Arcoíris",
    colors: [
      { name: "Rojo", hex: "#ef4444" },
      { name: "Naranja", hex: "#f97316" },
      { name: "Amarillo", hex: "#facc15" },
      { name: "Verde", hex: "#22c55e" },
      { name: "Azul", hex: "#3b82f6" },
      { name: "Indigo", hex: "#6366f1" },
      { name: "Violeta", hex: "#a855f7" },
    ],
  },
    {
    id: "spring",
    label: "Primavera",
    colors: [
      { name: "Melón", hex: "#FFD8A9" },
      { name: "Durazno", hex: "#FFBC9A" },
      { name: "Coral", hex: "#FF8882" },
      { name: "Turquesa claro", hex: "#A0E7E5" },
      { name: "Amarillo mantequilla", hex: "#FFFACD" },
    ],
  },
  {
    id: "summer",
    label: "Verano",
    colors: [
      { name: "Lavanda", hex: "#BFA2DB" },
      { name: "Rosa suave", hex: "#F9CEE7" },
      { name: "Azul polvo", hex: "#A3D2CA" },
      { name: "Gris azulado", hex: "#B0C4DE" },
      { name: "Malva", hex: "#D8B4E2" },
    ],
  },
  {
    id: "autumn",
    label: "Otoño",
    colors: [
      { name: "Mostaza", hex: "#D4A373" },
      { name: "Terracota", hex: "#E07A5F" },
      { name: "Oliva", hex: "#A98467" },
      { name: "Marrón", hex: "#7F5539" },
      { name: "Verde musgo", hex: "#588157" },
    ],
  },
  {
    id: "winter",
    label: "Invierno",
    colors: [
      { name: "Negro", hex: "#000000" },
      { name: "Gris carbón", hex: "#2E2E2E" },
      { name: "Blanco hielo", hex: "#F5F5F5" },
      { name: "Rojo rubí", hex: "#9B111E" },
      { name: "Azul marino", hex: "#0F4C81" },
    ],
  },
  {
    id: "earth",
    label: "Colores Tierra",
    colors: [
      { name: "Marrón Tierra", hex: "#92400e" },
      { name: "Arena", hex: "#ca8a04" },
      { name: "Verde Oliva", hex: "#6b7280" },
      { name: "Musgo", hex: "#4d7c0f" },
      { name: "Arcilla", hex: "#78350f" },
      { name: "Piedra", hex: "#64748b" },
      { name: "Gris Pizarra", hex: "#334155" },
      { name: "Tronco Oscuro", hex: "#43341b" },
    ],
  },
  {
    id: "pastel",
    label: "Pasteles",
    colors: [
      { name: "Rosa Pastel", hex: "#FADADD" },
      { name: "Azul Bebé", hex: "#A7C7E7" },
      { name: "Verde Menta", hex: "#C1E1C1" },
      { name: "Lavanda Suave", hex: "#E6E6FA" },
      { name: "Durazno Claro", hex: "#FFDAB9" },
      { name: "Amarillo Pálido", hex: "#FFFACD" },
      { name: "Celeste", hex: "#B3E5FC" },
      { name: "Lila Claro", hex: "#D8BFD8" },
      { name: "Verde Agua", hex: "#AFEEEE" },
      { name: "Melón Suave", hex: "#FFE5B4" },
    ],
  },
  {
    id: "neon",
    label: "Neón",
    colors: [
      { name: "Neón Rosa", hex: "#FF007F" },
      { name: "Neón Verde", hex: "#39FF14" },
      { name: "Neón Azul", hex: "#00FFFF" },
      { name: "Amarillo Eléctrico", hex: "#FFFF33" },
      { name: "Naranja Fuego", hex: "#FF5F1F" },
      { name: "Violeta Neón", hex: "#9D00FF" },
      { name: "Aqua Intenso", hex: "#00B7EB" },
      { name: "Magenta", hex: "#FF00FF" },
      { name: "Cian Brillante", hex: "#0FF0FC" },
      { name: "Verde Fosforescente", hex: "#7CFC00" },
    ],
  },
  {
    id: "vintage",
    label: "Vintage",
    colors: [
      { name: "Verde Oliva", hex: "#708238" },
      { name: "Naranja Oxidado", hex: "#C16E70" },
      { name: "Azul Apagado", hex: "#4682B4" },
      { name: "Mostaza Retro", hex: "#D4AF37" },
      { name: "Beige Antiguo", hex: "#C5B358" },
      { name: "Rosa Viejo", hex: "#C08081" },
      { name: "Turquesa Retro", hex: "#40E0D0" },
      { name: "Gris Vintage", hex: "#696969" },
      { name: "Marrón Cuero", hex: "#8B4513" },
    ],
  },
  {
    id: "metallic",
    label: "Metálicos",
    colors: [
      { name: "Oro", hex: "#FFD700" },
      { name: "Plata", hex: "#C0C0C0" },
      { name: "Bronce", hex: "#CD7F32" },
      { name: "Cobre", hex: "#B87333" },
      { name: "Acero", hex: "#8A8A8A" },
      { name: "Titanio", hex: "#778899" },
      { name: "Hierro Oscuro", hex: "#43464B" },
      { name: "Platino", hex: "#E5E4E2" },
    ],
  },
  {
    id: "grayscale",
    label: "Escala de Grises",
    colors: [
      { name: "Negro", hex: "#000000" },
      { name: "Gris Carbón", hex: "#1C1C1C" },
      { name: "Gris Oscuro", hex: "#2F4F4F" },
      { name: "Gris Medio", hex: "#696969" },
      { name: "Gris Claro", hex: "#BEBEBE" },
      { name: "Gris Plata", hex: "#D3D3D3" },
      { name: "Humo", hex: "#F5F5F5" },
      { name: "Blanco", hex: "#FFFFFF" },
    ],
  },
  {
    id: "luxury",
    label: "Lujo",
    colors: [
      { name: "Negro Onix", hex: "#0A0A0A" },
      { name: "Dorado Real", hex: "#FFD700" },
      { name: "Granate", hex: "#800000" },
      { name: "Esmeralda", hex: "#50C878" },
      { name: "Zafiro", hex: "#0F52BA" },
      { name: "Plata Brillante", hex: "#E5E4E2" },
      { name: "Champán", hex: "#F7E7CE" },
      { name: "Marfil", hex: "#FFFFF0" },
    ],
  },
  {
    id: "futuristic",
    label: "Futurista",
    colors: [
      { name: "Cian Digital", hex: "#00F0FF" },
      { name: "Magenta Luminiscente", hex: "#FF00E6" },
      { name: "Azul Holográfico", hex: "#3D5AFE" },
      { name: "Verde Neón", hex: "#00FF7F" },
      { name: "Blanco LED", hex: "#F8F9FA" },
      { name: "Gris Tech", hex: "#9E9E9E" },
      { name: "Violeta Cósmico", hex: "#8A2BE2" },
      { name: "Negro Espacial", hex: "#0D0D0D" },
    ],
  },
];